name: Node.js CI/CD Lightsail

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: |
        TIMESTAMP=$(date '+%Y_%m_%d_%H:%M:%S')
        BACKUP_DIR="/home/bitnami/backupAPI/backupDev_$TIMESTAMP"
        mkdir -p $BACKUP_DIR
        cp -r . $BACKUP_DIR || true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # ... other steps related to your Node.js setup, npm, and PM2 commands
