name: Node.js CI/CD Lightsail

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/bitnami/AnotherPath  # Change this to your desired path

    steps:
    - name: Checkout Repository to Another Path
      uses: actions/checkout@v3
      with:
        ref: 'master'
        path: "/home/bitnami/AnotherPath"  # Change this to your desired path
    # ... other steps in your workflow ...
