name: CICD

on:
  push:
    branches: mynod1

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t integrationninjas/nodejs-app .

      - name: Publish image to Docker Hub
        run: docker push integrationninjas/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull integrationninjas/nodejs-app:latest

      - name: Delete old container if exists
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container integrationninjas/nodejs-app
