name: Node.js CI/CD Lightsail

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Master Branch to Another Path
      uses: actions/checkout@v3
      with:
        ref: 'master'  # Specify the branch you want to checkout
        path: "/home/bitnami/API"  # Specify the desired path
    # ... other steps in your workflow ...
