name: Node.js CI/CD Lightsail

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Move Repository to /home/bitnami/API
        run: |
          mkdir -p /home/bitnami/API
          mv $GITHUB_WORKSPACE/* /home/bitnami/API/

      # The rest of your workflow steps go here...
